-- +migrate Up


CREATE TABLE IF NOT EXISTS carts (
    id SERIAL PRIMARY KEY,
    unique_id UUID DEFAULT gen_random_uuid() UNIQUE,
    user_id UUID NULL REFERENCES users(unique_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
